### PR TITLE
Web

### PR DESCRIPTION
**Pull request by chriamue**
Examples are cool but web examples are much cooler.
This merge request adds an wasm build and a build pipeline for github pages.
See the result at https://chriamue.github.io/mosse-tracker

### CODE REVIEW

**Comment by jjhbw** [comment]
This is a great idea!

I'm getting an error when trying your hosted demo in Chrome:
```
(index):50 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at (index):50:36
(anonymous) @ (index):50
```

**Comment by chriamue** [comment]
I think to remember that the page must loaded via https, which is given in the link, otherwise navigator.mediaDevices in
navigator.mediaDevices.getUserMedia is undefined. If the redirect didn't work, add https:// in front of the url.
I cannot remember if I additionally enabled some experimental features.
I am running chrome 104. Webcam has to be allowed.
Also tested on firefox 103.

**Comment by jjhbw** [comment]
That works! I got redirected to the plain http URL for some reason when I clicked your link. Really cool demo! I'll study the code a bit for my understanding and merge it.

**Comment by jjhbw** [comment]
Thanks again @chriamue  for this great idea! I put it up on my site as well https://barkeywolf.consulting/posts/mosse-tracker/

**Pull request merged**
